apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-1
  template:
    metadata:
      labels:
        app: deploy-1
        version: v1
    spec:
      containers:
      - image: jamesmilligan/basic-http
        name: deployment-1
        ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-1-service
spec:
  type: ClusterIP
  selector:
    app: deploy-1
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-2
  template:
    metadata:
      labels:
        app: deploy-2
        version: v1
    spec:
      containers:
      - image: jamesmilligan/basic-http
        name: deployment-2
        ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-2-service
spec:
  type: ClusterIP
  selector:
    app: deploy-2
  ports:
    - port: 8081
      targetPort: 8081